# Generated by Django 3.2.11 on 2022-01-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0006_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tagline',
            field=models.CharField(default='this was done without a tagline', max_length=50),
            preserve_default=False,
        ),
    ]
